version: "3.4"
x-restart-policy: &restart_policy
  restart: unless-stopped

services:

  # Databases
  database:
    <<: *restart_policy
    image: "postgres:12.2"
    environment:
      POSTGRES_DB: "root"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root!"
    ports:
      - "5432:5432"
    volumes:
      - "root-database:/var/lib/postgresql/data"
    networks:
      - internal

  mongo:
    <<: *restart_policy
    image: "mongo:6.0.5"
    volumes:
      - "root-mongo:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root!"
      MONGODB_AUTH_DATABASE: admin
    ports:
      - "27017:27017"
    networks:
      - internal

  # Visualization of the databases
  mongo-express:
    <<: *restart_policy
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: "root"
      ME_CONFIG_BASICAUTH_PASSWORD: "root!"
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "root!"
      ME_CONFIG_MONGODB_URL: mongodb://root:root!@mongo:27017/?authMechanism=DEFAULT
    depends_on:
      - mongo
    networks:
      - internal

  adminer:
    <<: *restart_policy
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - internal

  # Web
  web:
    <<: *restart_policy
    build:
      target: local
      context: root/
    working_dir: /home/ubuntu/webs/root/root
    command: ./bin/run.sh
    depends_on:
      - database
      - mongo
    ports:
      - "3031:3031"
      - "4444:4444"
      - "8000:8000"
    volumes:
      - ./root:/home/ubuntu/webs/root/root
    networks:
      - internal

volumes:
  root-database:
    external: true
  root-mongo:
    external: true
  root-redis:
    external: true

networks:
  internal:
    driver: bridge
